
name: aseprite

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        id: build
        shell: cmd
        run: call build.cmd

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}
          path: github
          if-no-files-found: error
